#!/bin/bash
echo 'Dom - Practica 5'
echo 'Directorio ráiz: $HOME/www/dom05'
echo 'Puerto TCP: 8085'
echo 'Nombre de host: dom05.com'
echo 'URL: http://dom05.com:8085'

directorioServidor=$HOME/www/dom05
puerto=8085
directorioArchivo=$HOME/Slackware/ShellScripts/Cliente/Dom/Practica_5

mkdir -p $directorioServidor
cd $directorioServidor

#Mover los siguientes archivos y directorios:
cp -a $directorioArchivo/index.html $directorioServidor
cp -a $directorioArchivo/css/  $directorioServidor
cp -a $directorioArchivo/js/  $directorioServidor
pwd && tree -L 2
#Iniciar servidor
thttpd -D -p $puerto -d $directorioServidor -nor -T UTF-8 -l -

