#!/bin/bash

echo ' = XMLHttpRequest - Practica 01 = '
echo 'Directorio ráiz: $HOME/www/xhr01'
echo 'Puerto TCP: 8081'
echo 'Nombre de host: xhr01.com'
echo 'URL: http://xhr01.com:8081'
echo ' = = = = = = = = = = = = = = = = = = = = = = = = = = = '
echo 'Nota: Asociar dirección ip 127.0.0.1 a xhr01.com en el archivo /etc/hosts'
echo ' = = = = = = = = = = = = = = = = = = = = = = = = = = = '
echo '1. Default'
echo '2. Personalizado'

#Ubicacion de archivos a utilizar
directorioArchivos=$HOME/Slackware/ShellScripts/Cliente/XmlHttpRequest/Practica_01
#Leer opcion
read opcion
# Opcion [Default]
if [ "$opcion" = "1" ]
	then
	#Variables	
	directorioServidor=$HOME/www/xhr01/
	puerto=8081
fi
# Opcion [Personalizado]
if [ "$opcion" = "2" ]
	then
	#Variables
	echo 'Ingrese la ruta del servidor:'
	read rutaServidor
	echo 'Ingrese el puerto a utilizar'
	read puertoPersonalizado
	#Asignar valores
	directorioServidor=$rutaServidor
	puerto=$puertoPersonalizado
fi
#Crear directorio raiz  
mkdir -p $directorioServidor
cd $directorioServidor

#Copiar archivo a servidor 
cp -a $directorioArchivos/index.html $directorioServidor
cp -a $directorioArchivos/js/ $directorioServidor
cp -a $directorioArchivos/xml/ $directorioServidor

#Iniciar Servidor web HTTP
echo 'Iniciando sevidor...'
thttpd -D -p $puerto -d $directorioServidor -nor -T UTF-8 -l -
pwd && tree
