#!/bin/bash
#Practica 2
echo 'Directorio ráiz: $HOME/www/ajedrez'
echo 'Nombre de host: ajedrez.com'
echo 'URL: http://ajedrez.com:8081'
echo ' = = = = = = = = = = = = = = = = = = = = = = = = = = = '
echo '1. Default'
echo '2. Establecer puerto ($HOME/www/ajedrez)'
echo '3. Establecer puerto y la ubicacion del servidor'
#Leer opcion
read opcion
# Opcion [Default]
if [ "$opcion" = "1" ]
        then
        echo 'Directorio servidor: $HOME/www/ajedrez'
        echo 'Puerto: 8081'
        #Variables
        directorioServidor=$HOME/www/ajedrez
        puerto=8081
fi
if [ "$opcion" = "2" ]
        then
        #Variables
        directorioServidor=$HOME/www/ajedrez
        echo 'Directorio servidor: $HOME/www/ajedrez'
        echo 'Ingrese el puerto a utilizar'
        read puertoPersonalizado
        puerto=$puertoPersonalizado
fi
if [ "$opcion" = "3" ]
        then
        #Variables
        echo 'Ingrese la directorio servidor:'
        read rutaServidor
        echo 'Ingrese el puerto a utilizar'
        read puertoPersonalizado
        #Asignar valores
        directorioServidor=$rutaServidor
        puerto=$puertoPersonalizado
fi

ubicacionArchivos=$HOME/Slackware/ShellScripts/Examen/ajedrez

mkdir -p $directorioServidor
cd $directorioServidor
#Copiar archivos a directorioServidor
cp -a $ubicacionArchivos/index.html $directorioServidor
cp -a $ubicacionArchivos/js $directorioServidor

#Iniciar servidor
thttpd -D -p $puerto -d $directorioServidor -nor -T UTF-8 -l -
